name: "Setup boost"
description: "Set boost url, target location and downloads if needed"
runs:
  using: "composite"
  steps:

    - name: Set boost env vars
      shell: sh
      run: |
        echo "BOOST_ROOT=${{github.workspace}}/3rdparty/boost" >> $GITHUB_ENV
        echo "BOOST_URL=https://sourceforge.net/projects/boost/files/boost/1.75.0/boost_1_75_0.tar.bz2/download" >> $GITHUB_ENV

    - name: Restore Boost cache
      uses: actions/cache@v2
      id: cache-boost
      with:
        path: ${{env.BOOST_ROOT}}
        key: ${{env.BOOST_URL}}

    - name: Install Boost
      shell: bash
      run: |
        if echo ${{ steps.cache-boost.outputs.cache-hit }} | grep -c "true"
        then
          echo "Using boost from cache"
        else
          echo "Downloading boost"
          if [ "$OS" == "Windows_NT" ]; then
            # fix up paths to be forward slashes consistently
            BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
          fi
          mkdir -p $BOOST_ROOT
          curl --progress-bar --location --output $BOOST_ROOT/download.tar.bz2 $BOOST_URL
          7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar.bz2 -y -bd
          7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar -y -bd
          cd $BOOST_ROOT && cp -r boost_*/* .
          rm -rf boost_*/* download.tar.bz2 download.tar
        fi
        


