language: cpp
sudo: true

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
     

before_install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt562

install:
 - sudo apt-get -qq update
 - sudo apt-get -qq install qt56base qt56tools qt56svg
 - sudo apt-get -qq install libboost-program-options-dev

before_script:
 - source /opt/qt56/bin/qt56-env.sh
 - g++-5 --version
 - qmake -v

script:
 - qmake QMAKE_CXX=g++-5 glogg.pro
 - make -j$(nproc)
