language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        artifacts: 
          paths:
            - ./build/output
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: ppa:beineri/opt-qt591-trusty
          packages:
            - gcc-6
            - g++-6
            - qt59base
      env: GCC_VERSION=6
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      addons:
        artifacts: 
          paths:
            - ./build/output

before_install:
 - '[ "$TRAVIS_OS_NAME" != osx   ] || brew update'

install:
 - '[ "$TRAVIS_OS_NAME" != osx ] || brew ls | grep -wq cmake || brew install cmake'
 - '[ "$TRAVIS_OS_NAME" != osx ] || brew ls | grep -wq qt5 || brew install qt5'

before_script:
 - '[ "$TRAVIS_OS_NAME" != linux ] || export CXX=g++-$GCC_VERSION CC=gcc-$GCC_VERSION'
 - '[ "$TRAVIS_OS_NAME" != linux ] || source /opt/qt59/bin/qt59-env.sh'
 - mkdir build
 - cd build
 - '[ "$TRAVIS_OS_NAME" != osx ] || cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$(brew --prefix qt5) ..'
 - '[ "$TRAVIS_OS_NAME" != linux ] || cmake -DCMAKE_BUILD_TYPE=Release ..'

script:
 - cmake --build .
 - ctest --verbose
