language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        addons:
          artifacts: 
            paths:
              - ./release
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: ppa:beineri/opt-qt591-trusty
          packages:
            - gcc-6
            - g++-6
            - qt59base
            - qt59tools
            - qt59svg
            - libboost-program-options-dev
    - os: osx
      compiler: clang
      addons:
        artifacts: 
          paths:
            - ./release

before_install:
 - '[ "$TRAVIS_OS_NAME" != osx   ] || brew update'

install:
 - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt5'
 - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt5'

before_script:
 - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
 - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
 - '[ "$TRAVIS_OS_NAME" != linux ] || source /opt/qt59/bin/qt59-env.sh'
 - qmake -v

script:
 - '[ "$TRAVIS_OS_NAME" != linux ] || qmake QMAKE_CXX=g++-6 glogg.pro'
 - '[ "$TRAVIS_OS_NAME" != osx ] || qmake glogg.pro'
 - make
