version: '1.1.3.{build}'

os: Visual Studio 2015

environment:
  matrix:
  - QT5: C:\Qt\5.9\msvc2015_64
  - QT5: C:\Qt\5.9\mingw53_32

matrix:
  fast_finish: false
  
before_build:
- '%QT5%\bin\qtenv2.bat'
- qmake -v

#- for /f %%i in ('git --git-dir=%APPVEYOR_BUILD_FOLDER%\.git describe') do set GLOGG_VERSION=%%i
#- for /f %%i in ('git --git-dir=%APPVEYOR_BUILD_FOLDER%\.git rev-parse --short HEAD') do set GLOGG_COMMIT=%%i

- set PATH=C:\Program Files (x86)\NSIS;%PATH%

# mingw
- if %QT5:msvc=%==%QT5% g++ --version
- if %QT5:msvc=%==%QT5% set make=mingw32-make.exe
- if %QT5:msvc=%==%QT5% %make% --version
- if %QT5:msvc=%==%QT5% set MINGW=C:\Qt\Tools\mingw530_32

# VS2015
- if not %QT5:msvc=%==%QT5% call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
- if not %QT5:msvc=%==%QT5% set make=nmake.exe
- if not %QT5:msvc=%==%QT5% %make% /? > nul

build_script:
- cd %APPVEYOR_BUILD_FOLDER%
- qmake -r VERSION=%APPVEYOR_BUILD_VERSION%
- '%make%'

after_build:
- xcopy %QT5%\bin\Qt5Core.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %QT5%\bin\Qt5Gui.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %QT5%\bin\Qt5Network.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %QT5%\bin\Qt5Widgets.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %QT5%\bin\Qt5Concurrent.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- md %APPVEYOR_BUILD_FOLDER%\release\platforms
- xcopy %QT5%\plugins\platforms\qminimal.dll %APPVEYOR_BUILD_FOLDER%\release\platforms\ /y
- xcopy %QT5%\plugins\platforms\qwindows.dll %APPVEYOR_BUILD_FOLDER%\release\platforms\ /y
- if %QT5:msvc=%==%QT5% xcopy %MINGW%\bin\libstdc++-6.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- if %QT5:msvc=%==%QT5% xcopy %MINGW%\bin\libgcc_s_dw2-1.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- if %QT5:msvc=%==%QT5% xcopy %MINGW%\bin\libwinpthread-1.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- 7z a klogg-%APPVEYOR_BUILD_VERSION%.zip -r %APPVEYOR_BUILD_FOLDER%\release\*.exe %APPVEYOR_BUILD_FOLDER%\release\*.dll %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\COPYING
- makensis -DVERSION=%APPVEYOR_BUILD_VERSION% %APPVEYOR_BUILD_FOLDER%\klogg.nsi

artifacts:
  - path: klogg-%APPVEYOR_BUILD_VERSION%.zip
    name: klogg
  - path: klogg-%APPVEYOR_BUILD_VERSION%-setup.exe
    name: installer
