version: '1.1.4.{build}'

os: Visual Studio 2015
platform:
  - x86
  - x64

environment:
  matrix:
  - QTDIR32: C:\Qt\5.12.4\mingw73_32
    QTDIR64: C:\Qt\5.12.4\mingw73_64
    BOOST_ROOT: C:\Libraries\boost_1_69_0
    MINGW_32: C:\Qt\Tools\mingw730_32
    MINGW_64: C:\Qt\Tools\mingw730_64
    NSIS: C:\Program Files (x86)\NSIS
    MAKE_CMD: mingw32-make

matrix:
    allow_failures:
    - platform: x86
    - platform: x64

before_build:
- if %platform%==x64 (set QT5=%QTDIR64%) else (set QT5=%QTDIR32%)
- if %platform%==x64 (set MINGW=%MINGW_64%) else (set MINGW=%MINGW_32%)
- if %platform%==x64 (set ERR_LIB=libgcc_s_seh-1.dll) else (set ERR_LIB=libgcc_s_dw2-1.dll)
- set PATH=%MINGW%\bin;%QT5%\bin;%NSIS%;%PATH%

build_script:
- qmake -v
- qmake -r BOOST_PATH=%BOOST_ROOT% VERSION="%APPVEYOR_BUILD_VERSION%"
- call %MAKE_CMD%

after_build:
- xcopy %QT5%\bin\Qt5Core.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %QT5%\bin\Qt5Gui.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %QT5%\bin\Qt5Network.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %QT5%\bin\Qt5Widgets.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %QT5%\bin\Qt5Concurrent.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- md %APPVEYOR_BUILD_FOLDER%\release\platforms
- xcopy %QT5%\plugins\platforms\qwindows.dll %APPVEYOR_BUILD_FOLDER%\release\platforms\ /y
- xcopy %MINGW%\bin\libstdc++-6.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %MINGW%\bin\%ERR_LIB% %APPVEYOR_BUILD_FOLDER%\release\ /y
- xcopy %MINGW%\bin\libwinpthread-1.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- 7z a glogg-%APPVEYOR_BUILD_VERSION%.zip -r %APPVEYOR_BUILD_FOLDER%\release\*.exe %APPVEYOR_BUILD_FOLDER%\release\*.dll README.md COPYING
- xcopy %QT5%\plugins\platforms\qwindows.dll %APPVEYOR_BUILD_FOLDER%\release\ /y
- makensis -DVERSION="%APPVEYOR_BUILD_VERSION%" -DPLATFORM=%PLATFORM% glogg.nsi

artifacts:
  - path: glogg-%APPVEYOR_BUILD_VERSION%.zip
    name: binary
  - path: glogg-%APPVEYOR_BUILD_VERSION%-setup.exe
    name: installer
