version: '{build}'

os: Visual Studio 2015

environment:
  matrix:
  - QT5: C:\Qt\5.9\mingw53_32
    BOOST_ROOT: C:\Libraries\boost_1_63_0
    MINGW: C:\Qt\Tools\mingw530_32
    MAKE_CMD: mingw32-make

matrix:
  fast_finish: true
  
before_build:
- set PATH=%MINGW%\bin;%QT5%\bin;%PATH%

build_script:
- qmake -v
- qmake -r BOOST_PATH=%BOOST_ROOT%
- call %MAKE_CMD%

after_build:
- xcopy %QT5%\bin\Qt5Core.dll %APPVEYOR_BUILD_FOLDER%\release\Qt5Core.dll /s /y
- xcopy %QT5%\bin\Qt5Gui.dll %APPVEYOR_BUILD_FOLDER%\release\Qt5Gui.dll /s /y
- xcopy %QT5%\bin\Qt5Network.dll %APPVEYOR_BUILD_FOLDER%\release\Qt5Network.dll /s /y
- xcopy %QT5%\bin\Qt5Widgets.dll %APPVEYOR_BUILD_FOLDER%\release\Qt5Widgets.dll /s /y
- xcopy %QT5%\bin\Qt5Concurrent.dll %APPVEYOR_BUILD_FOLDER%\release\Qt5Concurrent.dll /s /y
- xcopy %QT5%\plugins\platforms\* %APPVEYOR_BUILD_FOLDER%\release\ /s /y
- xcopy %QT5%\plugins\platforms\* %APPVEYOR_BUILD_FOLDER%\release\ /s /y
- xcopy %MINGW%\bin\libstdc++-6.dll %APPVEYOR_BUILD_FOLDER%\release\libstdc++-6.dll /s /y
- xcopy %MINGW%\bin\libgcc_s_dw2-1.dll %APPVEYOR_BUILD_FOLDER%\release\libgcc_s_dw2-1.dll /s /y
- xcopy %MINGW%\bin\libwinpthread-1.dll %APPVEYOR_BUILD_FOLDER%\release\libwinpthread-1.dll /s /y
- 7z a klogg.zip %APPVEYOR_BUILD_FOLDER%\release\*.*

artifacts:
  - path: klogg.zip
    name: klogg
