name: "Build and test one configuration"
description: "Generate the build files, build the code and run the tests"
runs:
  using: "composite"
  steps:

    - name: Prepare compiler env
      shell: sh
      run: |
        echo "CC=${{ matrix.config.cc }}" >> $GITHUB_ENV
        echo "CXX=${{ matrix.config.cxx }}" >> $GITHUB_ENV

    - name: configure
      shell: sh
      run: |
        mkdir $KLOGG_BUILD_ROOT
        cd $KLOGG_BUILD_ROOT
        cmake $KLOGG_CMAKE_OPTS $KLOGG_WORKSPACE

    - name: build
      shell: sh
      run: |
        cmake --build $KLOGG_BUILD_ROOT -t ci_build

    #- name: test
    #  shell: sh
    #  run: |
    #    cd $KLOGG_BUILD_ROOT
    #    ctest --verbose