name: "Make CI Release"

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci-build.yml
        workflow_conclusion: success
        branch: master

    - name: Initialize version
      run: echo "KLOGG_VERSION=`cat klogg_version/klogg_version.txt`" >> $GITHUB_ENV

    - name: Display structure of downloaded files
      run: ls -R

    






   