name: "Make CI Release"

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci-build.yml
        workflow_conclusion: success
        branch: master

    - name: Initialize version
      run: echo "KLOGG_VERSION=`cat klogg_version/klogg_version.txt`" >> $GITHUB_ENV

    - name: Display structure of downloaded files
      run: ls -R

    - name: Setup Sentry CLI
      uses: mathrix-education/setup-sentry-cli@0.1.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        token: ${{ secrets.SENTRY_TOKEN }}
        organization: anton-filimonov
        project: klogg

    - name: Create Sentry release
      shell: sh
      run: |
        sentry-cli releases new $KLOGG_VERSION
        sentry-cli releases set-commits --auto $KLOGG_VERSION

    - name: Upload symbols linux
      shell: sh
      run: |
        sentry-cli upload-dif ./packages-deb-x64/klogg_deb.sym 
        sentry-cli upload-dif ./packages-rpm-x64/klogg_rpm.sym 

    - name: Upload symbols mac
      shell: sh
      run: |
        sentry-cli upload-dif ./packages-macos-x64/klogg.app/Contents/MacOS/klogg ./packages-macos-x64/klogg.dSym

    - name: Upload symbols win x64
      shell: sh
      run: |
        sentry-cli upload-dif ./packages-windows-x64/klogg-$KLOGG_VERSION-x64-pdb.zip

    - name: Upload symbols win x86
      shell: sh
      run: |
        sentry-cli upload-dif ./packages-windows-x86/klogg-$KLOGG_VERSION-x86-pdb.zip 

    - name: Release win
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.KLOGG_GITHUB_TOKEN }}
        automatic_release_tag: continuous-win
        prerelease: true
        files: |
          ./packages-windows-x64/*
          ./packages-windows-x86/*

    - name: Release linux
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.KLOGG_GITHUB_TOKEN }}
        automatic_release_tag: continuous-linux
        prerelease: true
        files: |
          ./packages-deb-x64/*
          ./packages-rpm-x64/*

    - name: Release mac
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.KLOGG_GITHUB_TOKEN }}
        automatic_release_tag: continuous-osx
        prerelease: true
        files: ./packages-macos-x64/*

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_NEW_VERSIONS_WEBHOOK }}
        DISCORD_EMBEDS: { [{"title": "Windows", "url": "https://github.com/variar/klogg/releases/tag/continuous-win"}], [{"title": "Linux", "url": "https://github.com/variar/klogg/releases/tag/continuous-linux"}], [{"title": "Mac", "url": "https://github.com/variar/klogg/releases/tag/continuous-osx"}] }
      uses: Ilshidur/action-discord@master
      with:
        args: 'New CI build {{KLOGG_VERSION}} has been released!'



   